### ISSUE TITLE
oss repo - error with PDepend, parser issue?

### ISSUE THREAD

**Issue by efueger** [codeclimate/codeclimate-phpmd#47]
https://github.com/FrailmoonEnterprises/AlivarAPI

OSS repo erroring with:

```
engine phpmd failed with status 1 and stderr 
Exception: Argument 1 passed to PDepend\Source\Parser\TokenStack::add() must be an instance of PDepend\Source\Tokenizer\Token, integer given, called in /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php on line 6842 in /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Parser/TokenStack.php
#0 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(6842): PDepend\Source\Parser\TokenStack->add(-1)
#1 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2587): PDepend\Source\Language\PHP\AbstractPHPParser->consumeToken(-1)
#2 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5039): PDepend\Source\Language\PHP\AbstractPHPParser->parseExpression()
#3 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4996): PDepend\Source\Language\PHP\AbstractPHPParser->parseArrayElement(false)
#4 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion53.php(91): PDepend\Source\Language\PHP\AbstractPHPParser->parseArrayElements(Object(PDepend\Source\AST\ASTArray), 7, false)
#5 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion54.php(216): PDepend\Source\Language\PHP\PHPParserVersion53->parseArray(Object(PDepend\Source\AST\ASTArray), false)
#6 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4957): PDepend\Source\Language\PHP\PHPParserVersion54->parseArray(Object(PDepend\Source\AST\ASTArray), false)
#7 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2653): PDepend\Source\Language\PHP\AbstractPHPParser->doParseArray()
#8 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2586): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpression()
#9 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5049): PDepend\Source\Language\PHP\AbstractPHPParser->parseExpression()
#10 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4996): PDepend\Source\Language\PHP\AbstractPHPParser->parseArrayElement(false)
#11 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion53.php(91): PDepend\Source\Language\PHP\AbstractPHPParser->parseArrayElements(Object(PDepend\Source\AST\ASTArray), 7, false)
#12 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion54.php(216): PDepend\Source\Language\PHP\PHPParserVersion53->parseArray(Object(PDepend\Source\AST\ASTArray), false)
#13 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4957): PDepend\Source\Language\PHP\PHPParserVersion54->parseArray(Object(PDepend\Source\AST\ASTArray), false)
#14 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2653): PDepend\Source\Language\PHP\AbstractPHPParser->doParseArray()
#15 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(4354): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpression()
#16 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(2774): PDepend\Source\Language\PHP\AbstractPHPParser->parseAssignmentExpression(Object(PDepend\Source\AST\ASTArrayIndexExpression))
#17 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(5725): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalExpression()
#18 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(388): PDepend\Source\Language\PHP\AbstractPHPParser->parseOptionalStatement()
#19 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(575): PDepend\Source\Language\PHP\AbstractPHPParser->parse()
#20 /usr/src/app/vendor/pdepend/pdepend/src/main/php/PDepend/Engine.php(323): PDepend\Engine->performParseProcess()
#21 /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(123): PDepend\Engine->analyze()
#22 /usr/src/app/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(222): PHPMD\Parser->parse(Object(PHPMD\Report))
#23 /usr/src/app/Runner.php(116): PHPMD\PHPMD->processFiles('/code/user/inst...', 'cleancode,codes...', Array, Object(PHPMD\RuleSetFactory))
#24 /usr/src/app/vendor/barracudanetworks/forkdaemon-php/fork_daemon.php(1852): CodeClimate\PHPMD\Runner->run(Array)
#25 /usr/src/app/vendor/barracudanetworks/forkdaemon-php/fork_daemon.php(1772): fork_daemon->invoke_callback(Array, Array, false)
#26 /usr/src/app/vendor/barracudanetworks/forkdaemon-php/fork_daemon.php(1673): fork_daemon->fork_work_unit(Array, '', -1)
#27 /usr/src/app/vendor/barracudanetworks/forkdaemon-php/fork_daemon.php(1423): fork_daemon->process_work_unit(-1)
#28 /usr/src/app/engine.php(37): fork_daemon->process_work(true)
#29 {main}
```

- Happens with Code Climate CLI and .com analysis.
- checking with @powelljf3 to see if he can reproduce with PHPMD itself, locally

**Comment by efueger** [comment]
@katwchen - bump 👆

**Comment by powelljf3** [comment]
I did check locally, it took a couple of days to get the local system setup on limited time, I'm not seeing the error on my local system.
